services:
  mozart:
    build: .
    image: renx86/mozart:latest
    container_name: mozart
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - PORT=5000
      - FLASK_ENV=production
    volumes:
      # Mount the data directory for persistence
      - ./src/data:/app/src/data
